// Objective-C API for talking to github.com/sagernet/sing-box/experimental/libbox Go package.
//   gobind -lang=objc github.com/sagernet/sing-box/experimental/libbox
//
// File is generated by gobind. Do not edit.

#ifndef __Libbox_H__
#define __Libbox_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibboxBridgeOptions;
@class LibboxCommandClient;
@class LibboxCommandClientOptions;
@class LibboxCommandServer;
@class LibboxConnection;
@class LibboxConnectionEvent;
@class LibboxConnectionEvents;
@class LibboxConnectionOwner;
@class LibboxConnections;
@class LibboxDeprecatedNote;
@class LibboxErrorMessage;
@class LibboxExchangeContext;
@class LibboxFDroidMirror;
@class LibboxFDroidPingResult;
@class LibboxFDroidUpdateInfo;
@class LibboxImportRemoteProfile;
@class LibboxLogEntry;
@class LibboxNeighborEntry;
@class LibboxNeighborSubscription;
@class LibboxNetworkInterface;
@class LibboxNetworkQualityProgress;
@class LibboxNetworkQualityResult;
@class LibboxNetworkQualityTest;
@class LibboxNetworkQualityTestSession;
@class LibboxNotification;
@class LibboxOutboundGroup;
@class LibboxOutboundGroupItem;
@class LibboxOverrideOptions;
@class LibboxPProfServer;
@class LibboxPlatformUser;
@class LibboxProcessInfo;
@class LibboxProfileContent;
@class LibboxProfileContentRequest;
@class LibboxProfileDecoder;
@class LibboxProfileEncoder;
@class LibboxProfilePreview;
@class LibboxRemoteConnectionOptions;
@class LibboxRoutePrefix;
@class LibboxSTUNTest;
@class LibboxSTUNTestProgress;
@class LibboxSTUNTestResult;
@class LibboxSTUNTestSession;
@class LibboxSetupOptions;
@class LibboxStatusMessage;
@class LibboxStringBox;
@class LibboxSystemProxyStatus;
@class LibboxTailscaleEndpointStatus;
@class LibboxTailscalePeer;
@class LibboxTailscalePingResult;
@class LibboxTailscalePingSession;
@class LibboxTailscaleSSHOptions;
@class LibboxTailscaleSSHSession;
@class LibboxTailscaleStatusSubscription;
@class LibboxTailscaleStatusUpdate;
@class LibboxTailscaleUserGroup;
@class LibboxUSBDeviceDescriptor;
@class LibboxUSBIPServerStatus;
@class LibboxUSBIPServerStatusSubscription;
@class LibboxUSBIPServerStatusUpdate;
@class LibboxUSBIsoPacket;
@class LibboxUSBLocalDeviceInfo;
@class LibboxUSBLocalProvidedDevice;
@class LibboxUSBLocalProviderManager;
@class LibboxUSBProviderSession;
@class LibboxUSBSharedDevice;
@class LibboxUSBSharedDeviceInterface;
@class LibboxUSBURBRequest;
@class LibboxUSBURBResponse;
@class LibboxWIFIState;
@protocol LibboxBridgeSession;
@class LibboxBridgeSession;
@protocol LibboxCommandClientHandler;
@class LibboxCommandClientHandler;
@protocol LibboxCommandServerHandler;
@class LibboxCommandServerHandler;
@protocol LibboxConnectionEventIterator;
@class LibboxConnectionEventIterator;
@protocol LibboxConnectionIterator;
@class LibboxConnectionIterator;
@protocol LibboxDeprecatedNoteIterator;
@class LibboxDeprecatedNoteIterator;
@protocol LibboxFDroidMirrorIterator;
@class LibboxFDroidMirrorIterator;
@protocol LibboxFDroidPingResultIterator;
@class LibboxFDroidPingResultIterator;
@protocol LibboxFunc;
@class LibboxFunc;
@protocol LibboxHTTPClient;
@class LibboxHTTPClient;
@protocol LibboxHTTPRequest;
@class LibboxHTTPRequest;
@protocol LibboxHTTPResponse;
@class LibboxHTTPResponse;
@protocol LibboxHTTPResponseWriteToProgressHandler;
@class LibboxHTTPResponseWriteToProgressHandler;
@protocol LibboxInt32Iterator;
@class LibboxInt32Iterator;
@protocol LibboxInterfaceUpdateListener;
@class LibboxInterfaceUpdateListener;
@protocol LibboxLocalDNSTransport;
@class LibboxLocalDNSTransport;
@protocol LibboxLogIterator;
@class LibboxLogIterator;
@protocol LibboxNeighborEntryIterator;
@class LibboxNeighborEntryIterator;
@protocol LibboxNeighborUpdateListener;
@class LibboxNeighborUpdateListener;
@protocol LibboxNetworkInterfaceIterator;
@class LibboxNetworkInterfaceIterator;
@protocol LibboxNetworkQualityTestHandler;
@class LibboxNetworkQualityTestHandler;
@protocol LibboxOnDemandRule;
@class LibboxOnDemandRule;
@protocol LibboxOnDemandRuleIterator;
@class LibboxOnDemandRuleIterator;
@protocol LibboxOutboundGroupItemIterator;
@class LibboxOutboundGroupItemIterator;
@protocol LibboxOutboundGroupIterator;
@class LibboxOutboundGroupIterator;
@protocol LibboxPlatformInterface;
@class LibboxPlatformInterface;
@protocol LibboxProfilePreviewIterator;
@class LibboxProfilePreviewIterator;
@protocol LibboxRoutePrefixIterator;
@class LibboxRoutePrefixIterator;
@protocol LibboxSTUNTestHandler;
@class LibboxSTUNTestHandler;
@protocol LibboxShellSession;
@class LibboxShellSession;
@protocol LibboxStringIterator;
@class LibboxStringIterator;
@protocol LibboxTailscaleEndpointStatusIterator;
@class LibboxTailscaleEndpointStatusIterator;
@protocol LibboxTailscalePeerIterator;
@class LibboxTailscalePeerIterator;
@protocol LibboxTailscalePingHandler;
@class LibboxTailscalePingHandler;
@protocol LibboxTailscaleSSHHandler;
@class LibboxTailscaleSSHHandler;
@protocol LibboxTailscaleStatusHandler;
@class LibboxTailscaleStatusHandler;
@protocol LibboxTailscaleUserGroupIterator;
@class LibboxTailscaleUserGroupIterator;
@protocol LibboxTunOptions;
@class LibboxTunOptions;
@protocol LibboxUSBIPServerStatusHandler;
@class LibboxUSBIPServerStatusHandler;
@protocol LibboxUSBIPServerStatusIterator;
@class LibboxUSBIPServerStatusIterator;
@protocol LibboxUSBLocalDeviceInfoIterator;
@class LibboxUSBLocalDeviceInfoIterator;
@protocol LibboxUSBLocalProviderHandler;
@class LibboxUSBLocalProviderHandler;
@protocol LibboxUSBProviderHandler;
@class LibboxUSBProviderHandler;
@protocol LibboxUSBSharedDeviceInterfaceIterator;
@class LibboxUSBSharedDeviceInterfaceIterator;
@protocol LibboxUSBSharedDeviceIterator;
@class LibboxUSBSharedDeviceIterator;
@protocol LibboxXPCDialer;
@class LibboxXPCDialer;

@protocol LibboxBridgeSession <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (int32_t)fileDescriptor;
- (BOOL)inet6Active;
- (NSString* _Nonnull)name;
- (BOOL)setEgress:(NSString* _Nullable)interfaceName error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibboxCommandClientHandler <NSObject>
- (void)clearLogs;
- (void)connected;
- (void)disconnected:(NSString* _Nullable)message;
- (void)initializeClashMode:(id<LibboxStringIterator> _Nullable)modeList currentMode:(NSString* _Nullable)currentMode;
- (void)setDefaultLogLevel:(int32_t)level;
- (void)updateClashMode:(NSString* _Nullable)newMode;
- (void)writeConnectionEvents:(LibboxConnectionEvents* _Nullable)events;
- (void)writeGroups:(id<LibboxOutboundGroupIterator> _Nullable)message;
- (void)writeLogs:(id<LibboxLogIterator> _Nullable)messageList;
- (void)writeOutbounds:(id<LibboxOutboundGroupItemIterator> _Nullable)message;
- (void)writeStatus:(LibboxStatusMessage* _Nullable)message;
@end

@protocol LibboxCommandServerHandler <NSObject>
- (BOOL)connectSSHAgent:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (LibboxSystemProxyStatus* _Nullable)getSystemProxyStatus:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceStop:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)enabled error:(NSError* _Nullable* _Nullable)error;
- (BOOL)triggerNativeCrash:(NSError* _Nullable* _Nullable)error;
- (void)writeDebugMessage:(NSString* _Nullable)message;
@end

@protocol LibboxConnectionEventIterator <NSObject>
- (BOOL)hasNext;
- (LibboxConnectionEvent* _Nullable)next;
@end

@protocol LibboxConnectionIterator <NSObject>
- (BOOL)hasNext;
- (LibboxConnection* _Nullable)next;
@end

@protocol LibboxDeprecatedNoteIterator <NSObject>
- (BOOL)hasNext;
- (LibboxDeprecatedNote* _Nullable)next;
@end

@protocol LibboxFDroidMirrorIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidMirror* _Nullable)next;
@end

@protocol LibboxFDroidPingResultIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidPingResult* _Nullable)next;
@end

@protocol LibboxFunc <NSObject>
- (BOOL)invoke:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibboxHTTPClient <NSObject>
- (void)close;
- (void)keepAlive;
- (void)modernTLS;
- (id<LibboxHTTPRequest> _Nullable)newRequest;
- (void)pinnedSHA256:(NSString* _Nullable)sumHex;
- (void)pinnedTLS12;
- (void)restrictedTLS;
- (void)trySocks5:(int32_t)port;
@end

@protocol LibboxHTTPRequest <NSObject>
- (id<LibboxHTTPResponse> _Nullable)execute:(NSError* _Nullable* _Nullable)error;
- (void)randomUserAgent;
- (void)setContent:(NSData* _Nullable)content;
- (void)setContentString:(NSString* _Nullable)content;
- (void)setHeader:(NSString* _Nullable)key value:(NSString* _Nullable)value;
- (void)setMethod:(NSString* _Nullable)method;
- (BOOL)setURL:(NSString* _Nullable)link error:(NSError* _Nullable* _Nullable)error;
- (void)setUserAgent:(NSString* _Nullable)userAgent;
@end

@protocol LibboxHTTPResponse <NSObject>
- (LibboxStringBox* _Nullable)getContent:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeTo:(NSString* _Nullable)path error:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeToWithProgress:(NSString* _Nullable)path handler:(id<LibboxHTTPResponseWriteToProgressHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibboxHTTPResponseWriteToProgressHandler <NSObject>
- (void)update:(int64_t)progress total:(int64_t)total;
@end

@protocol LibboxInt32Iterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (int32_t)next;
@end

@protocol LibboxInterfaceUpdateListener <NSObject>
- (void)updateDefaultInterface:(NSString* _Nullable)interfaceName interfaceIndex:(int32_t)interfaceIndex isExpensive:(BOOL)isExpensive isConstrained:(BOOL)isConstrained;
@end

@protocol LibboxLocalDNSTransport <NSObject>
- (BOOL)exchange:(LibboxExchangeContext* _Nullable)ctx message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
- (BOOL)lookup:(LibboxExchangeContext* _Nullable)ctx network:(NSString* _Nullable)network domain:(NSString* _Nullable)domain error:(NSError* _Nullable* _Nullable)error;
- (BOOL)raw;
@end

@protocol LibboxLogIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxLogEntry* _Nullable)next;
@end

@protocol LibboxNeighborEntryIterator <NSObject>
- (BOOL)hasNext;
- (LibboxNeighborEntry* _Nullable)next;
@end

@protocol LibboxNeighborUpdateListener <NSObject>
- (void)updateNeighborTable:(id<LibboxNeighborEntryIterator> _Nullable)entries;
@end

@protocol LibboxNetworkInterfaceIterator <NSObject>
- (BOOL)hasNext;
- (LibboxNetworkInterface* _Nullable)next;
@end

@protocol LibboxNetworkQualityTestHandler <NSObject>
- (void)onError:(NSString* _Nullable)message;
- (void)onProgress:(LibboxNetworkQualityProgress* _Nullable)progress;
- (void)onResult:(LibboxNetworkQualityResult* _Nullable)result;
@end

@protocol LibboxOnDemandRule <NSObject>
- (id<LibboxStringIterator> _Nullable)dnsSearchDomainMatch;
- (id<LibboxStringIterator> _Nullable)dnsServerAddressMatch;
- (int32_t)interfaceTypeMatch;
- (NSString* _Nonnull)probeURL;
- (id<LibboxStringIterator> _Nullable)ssidMatch;
- (int32_t)target;
@end

@protocol LibboxOnDemandRuleIterator <NSObject>
- (BOOL)hasNext;
- (id<LibboxOnDemandRule> _Nullable)next;
@end

@protocol LibboxOutboundGroupItemIterator <NSObject>
- (BOOL)hasNext;
- (LibboxOutboundGroupItem* _Nullable)next;
@end

@protocol LibboxOutboundGroupIterator <NSObject>
- (BOOL)hasNext;
- (LibboxOutboundGroup* _Nullable)next;
@end

@protocol LibboxPlatformInterface <NSObject>
- (BOOL)autoDetectInterfaceControl:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (BOOL)checkPlatformShell:(NSError* _Nullable* _Nullable)error;
- (void)clearDNSCache;
- (BOOL)closeDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)closeNeighborMonitor:(id<LibboxNeighborUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxBridgeSession> _Nullable)createBridge:(LibboxBridgeOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
- (LibboxConnectionOwner* _Nullable)findConnectionOwner:(int32_t)ipProtocol sourceAddress:(NSString* _Nullable)sourceAddress sourcePort:(int32_t)sourcePort destinationAddress:(NSString* _Nullable)destinationAddress destinationPort:(int32_t)destinationPort error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxNetworkInterfaceIterator> _Nullable)getInterfaces:(NSError* _Nullable* _Nullable)error;
- (BOOL)includeAllNetworks;
- (id<LibboxLocalDNSTransport> _Nullable)localDNSTransport;
- (NSString* _Nonnull)lookupSFTPServer:(NSError* _Nullable* _Nullable)error;
- (LibboxPlatformUser* _Nullable)lookupUser:(NSString* _Nullable)username error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxShellSession> _Nullable)openShellSession:(LibboxPlatformUser* _Nullable)user command:(NSString* _Nullable)command environ:(id<LibboxStringIterator> _Nullable)environ term:(NSString* _Nullable)term rows:(int32_t)rows cols:(int32_t)cols error:(NSError* _Nullable* _Nullable)error;
- (BOOL)openTun:(id<LibboxTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)readSystemSSHHostKey:(NSError* _Nullable* _Nullable)error;
- (LibboxWIFIState* _Nullable)readWIFIState;
- (void)registerMyInterface:(NSString* _Nullable)name;
- (BOOL)sendNotification:(LibboxNotification* _Nullable)notification error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startNeighborMonitor:(id<LibboxNeighborUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)tailscaleHostname;
- (BOOL)underNetworkExtension;
- (BOOL)usePlatformAutoDetectInterfaceControl;
- (BOOL)usePlatformBridge;
- (BOOL)usePlatformShell;
- (BOOL)useProcFS;
@end

@protocol LibboxProfilePreviewIterator <NSObject>
- (BOOL)hasNext;
- (LibboxProfilePreview* _Nullable)next;
@end

@protocol LibboxRoutePrefixIterator <NSObject>
- (BOOL)hasNext;
- (LibboxRoutePrefix* _Nullable)next;
@end

@protocol LibboxSTUNTestHandler <NSObject>
- (void)onError:(NSString* _Nullable)message;
- (void)onProgress:(LibboxSTUNTestProgress* _Nullable)progress;
- (void)onResult:(LibboxSTUNTestResult* _Nullable)result;
@end

@protocol LibboxShellSession <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (int32_t)masterFD;
- (BOOL)resize:(int32_t)rows cols:(int32_t)cols error:(NSError* _Nullable* _Nullable)error;
- (BOOL)signal:(int32_t)signal error:(NSError* _Nullable* _Nullable)error;
- (BOOL)waitExit:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibboxStringIterator <NSObject>
- (BOOL)hasNext;
- (int32_t)len;
- (NSString* _Nonnull)next;
@end

@protocol LibboxTailscaleEndpointStatusIterator <NSObject>
- (BOOL)hasNext;
- (LibboxTailscaleEndpointStatus* _Nullable)next;
@end

@protocol LibboxTailscalePeerIterator <NSObject>
- (BOOL)hasNext;
- (LibboxTailscalePeer* _Nullable)next;
@end

@protocol LibboxTailscalePingHandler <NSObject>
- (void)onError:(NSString* _Nullable)message;
- (void)onPingResult:(LibboxTailscalePingResult* _Nullable)result;
@end

@protocol LibboxTailscaleSSHHandler <NSObject>
- (void)onAuthBanner:(NSString* _Nullable)message;
- (void)onError:(NSString* _Nullable)message;
- (void)onExit:(int32_t)exitCode signal:(NSString* _Nullable)signal errorMessage:(NSString* _Nullable)errorMessage;
- (void)onOutput:(NSData* _Nullable)data;
- (void)onReady;
@end

@protocol LibboxTailscaleStatusHandler <NSObject>
- (void)onError:(NSString* _Nullable)message;
- (void)onStatusUpdate:(LibboxTailscaleStatusUpdate* _Nullable)status;
@end

@protocol LibboxTailscaleUserGroupIterator <NSObject>
- (BOOL)hasNext;
- (LibboxTailscaleUserGroup* _Nullable)next;
@end

@protocol LibboxTunOptions <NSObject>
- (BOOL)getAutoRoute;
- (LibboxStringBox* _Nullable)getDNSMode;
- (id<LibboxStringIterator> _Nullable)getDNSServerAddress:(NSError* _Nullable* _Nullable)error;
- (id<LibboxStringIterator> _Nullable)getExcludePackage;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyBypassDomain;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyMatchDomain;
- (NSString* _Nonnull)getHTTPProxyServer;
- (int32_t)getHTTPProxyServerPort;
- (id<LibboxStringIterator> _Nullable)getIncludePackage;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteRange;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteRange;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
- (BOOL)isHTTPProxyEnabled;
@end

@protocol LibboxUSBIPServerStatusHandler <NSObject>
- (void)onError:(NSString* _Nullable)message;
- (void)onStatusUpdate:(LibboxUSBIPServerStatusUpdate* _Nullable)status;
@end

@protocol LibboxUSBIPServerStatusIterator <NSObject>
- (BOOL)hasNext;
- (LibboxUSBIPServerStatus* _Nullable)next;
@end

@protocol LibboxUSBLocalDeviceInfoIterator <NSObject>
- (BOOL)hasNext;
- (LibboxUSBLocalDeviceInfo* _Nullable)next;
@end

@protocol LibboxUSBLocalProviderHandler <NSObject>
- (void)onDeviceError:(NSString* _Nullable)serverTag deviceID:(NSString* _Nullable)deviceID message:(NSString* _Nullable)message;
- (void)onLocalDevicesChanged;
- (void)onSessionError:(NSString* _Nullable)serverTag message:(NSString* _Nullable)message;
@end

@protocol LibboxUSBProviderHandler <NSObject>
- (void)onAbort:(NSString* _Nullable)deviceID endpoint:(int32_t)endpoint;
- (void)onError:(NSString* _Nullable)deviceID message:(NSString* _Nullable)message;
- (void)onReady:(NSString* _Nullable)deviceID busID:(NSString* _Nullable)busID;
- (void)onURBRequest:(LibboxUSBURBRequest* _Nullable)request;
@end

@protocol LibboxUSBSharedDeviceInterfaceIterator <NSObject>
- (BOOL)hasNext;
- (LibboxUSBSharedDeviceInterface* _Nullable)next;
@end

@protocol LibboxUSBSharedDeviceIterator <NSObject>
- (BOOL)hasNext;
- (LibboxUSBSharedDevice* _Nullable)next;
@end

@protocol LibboxXPCDialer <NSObject>
- (BOOL)dialXPC:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxBridgeOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setBridgeName:) NSString* _Nonnull bridgeName;
@property (nonatomic, setter=setMTU:) int32_t mtu;
@property (nonatomic, setter=setInet4Port:) NSString* _Nonnull inet4Port;
@property (nonatomic, setter=setInet6Port:) NSString* _Nonnull inet6Port;
@property (nonatomic, setter=setInterface:) NSString* _Nonnull interface;
@property (nonatomic, setter=setRuleIndex:) int32_t ruleIndex;
@property (nonatomic, setter=setRouteTable:) int32_t routeTable;
@end

@interface LibboxCommandClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<LibboxCommandClientHandler> _Nullable)handler options:(LibboxCommandClientOptions* _Nullable)options;
- (BOOL)clearLogs:(NSError* _Nullable* _Nullable)error;
- (BOOL)closeConnection:(NSString* _Nullable)connId error:(NSError* _Nullable* _Nullable)error;
- (BOOL)closeConnections:(NSError* _Nullable* _Nullable)error;
- (BOOL)connect:(NSError* _Nullable* _Nullable)error;
- (BOOL)connectWithFD:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (BOOL)disconnect:(NSError* _Nullable* _Nullable)error;
- (BOOL)getAPIVersion:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxDeprecatedNoteIterator> _Nullable)getDeprecatedNotes:(NSError* _Nullable* _Nullable)error;
- (BOOL)getStartedAt:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (LibboxSystemProxyStatus* _Nullable)getSystemProxyStatus:(NSError* _Nullable* _Nullable)error;
- (LibboxUSBLocalProviderManager* _Nullable)newUSBLocalProvider:(id<LibboxUSBLocalProviderHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (LibboxUSBProviderSession* _Nullable)provideUSBDevices:(id<LibboxUSBProviderHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (BOOL)selectOutbound:(NSString* _Nullable)groupTag outboundTag:(NSString* _Nullable)outboundTag error:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceClose:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)setClashMode:(NSString* _Nullable)newMode error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setGroupExpand:(NSString* _Nullable)groupTag isExpand:(BOOL)isExpand error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)isEnabled error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setTailscaleExitNode:(NSString* _Nullable)endpointTag stableID:(NSString* _Nullable)stableID error:(NSError* _Nullable* _Nullable)error;
- (LibboxNetworkQualityTestSession* _Nullable)startNetworkQualityTest:(NSString* _Nullable)configURL outboundTag:(NSString* _Nullable)outboundTag serial:(BOOL)serial maxRuntimeSeconds:(int32_t)maxRuntimeSeconds http3:(BOOL)http3 handler:(id<LibboxNetworkQualityTestHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (LibboxSTUNTestSession* _Nullable)startSTUNTest:(NSString* _Nullable)server outboundTag:(NSString* _Nullable)outboundTag handler:(id<LibboxSTUNTestHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (LibboxTailscalePingSession* _Nullable)startTailscalePing:(NSString* _Nullable)endpointTag peerIP:(NSString* _Nullable)peerIP handler:(id<LibboxTailscalePingHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (LibboxTailscaleSSHSession* _Nullable)startTailscaleSSHSession:(LibboxTailscaleSSHOptions* _Nullable)opts handler:(id<LibboxTailscaleSSHHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (LibboxTailscaleStatusSubscription* _Nullable)subscribeTailscaleStatus:(id<LibboxTailscaleStatusHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (LibboxUSBIPServerStatusSubscription* _Nullable)subscribeUSBIPServerStatus:(id<LibboxUSBIPServerStatusHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
- (BOOL)tailscaleLogout:(NSString* _Nullable)endpointTag error:(NSError* _Nullable* _Nullable)error;
- (BOOL)triggerGoCrash:(NSError* _Nullable* _Nullable)error;
- (BOOL)triggerNativeCrash:(NSError* _Nullable* _Nullable)error;
- (BOOL)triggerOOMReport:(NSError* _Nullable* _Nullable)error;
- (BOOL)urlTest:(NSString* _Nullable)groupTag error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxCommandClientOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setStatusInterval:) int64_t statusInterval;
- (void)addCommand:(int32_t)command;
@end

@interface LibboxCommandServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<LibboxCommandServerHandler> _Nullable)handler platformInterface:(id<LibboxPlatformInterface> _Nullable)platformInterface;
// skipped field CommandServer.StartedService with unsupported type: *github.com/sagernet/sing-box/daemon.StartedService

- (BOOL)checkConfig:(NSString* _Nullable)configContent error:(NSError* _Nullable* _Nullable)error;
// skipped method CommandServer.ClearLogs with unsupported parameter or return types

- (void)close;
// skipped method CommandServer.CloseAllConnections with unsupported parameter or return types

// skipped method CommandServer.CloseConnection with unsupported parameter or return types

- (BOOL)closeService:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)formatConfig:(NSString* _Nullable)configContent error:(NSError* _Nullable* _Nullable)error;
// skipped method CommandServer.GetClashModeStatus with unsupported parameter or return types

// skipped method CommandServer.GetDefaultLogLevel with unsupported parameter or return types

// skipped method CommandServer.GetDeprecatedWarnings with unsupported parameter or return types

// skipped method CommandServer.GetStartedAt with unsupported parameter or return types

// skipped method CommandServer.GetVersion with unsupported parameter or return types

// skipped method CommandServer.Instance with unsupported parameter or return types

- (BOOL)needFindProcess;
- (BOOL)needWIFIState;
- (void)pause;
// skipped method CommandServer.ProvideUSBDevices with unsupported parameter or return types

- (void)resetNetwork;
// skipped method CommandServer.SavedLog with unsupported parameter or return types

// skipped method CommandServer.SelectOutbound with unsupported parameter or return types

// skipped method CommandServer.SetClashMode with unsupported parameter or return types

- (void)setError:(NSString* _Nullable)message;
// skipped method CommandServer.SetGroupExpand with unsupported parameter or return types

// skipped method CommandServer.SetTailscaleExitNode with unsupported parameter or return types

- (BOOL)start:(NSError* _Nullable* _Nullable)error;
// skipped method CommandServer.StartNetworkQualityTest with unsupported parameter or return types

- (BOOL)startOrReloadService:(NSString* _Nullable)configContent options:(LibboxOverrideOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
// skipped method CommandServer.StartSTUNTest with unsupported parameter or return types

// skipped method CommandServer.StartTailscalePing with unsupported parameter or return types

// skipped method CommandServer.StartTailscaleSSHSession with unsupported parameter or return types

// skipped method CommandServer.SubscribeClashMode with unsupported parameter or return types

// skipped method CommandServer.SubscribeConnections with unsupported parameter or return types

// skipped method CommandServer.SubscribeGroups with unsupported parameter or return types

// skipped method CommandServer.SubscribeLog with unsupported parameter or return types

// skipped method CommandServer.SubscribeOutbounds with unsupported parameter or return types

// skipped method CommandServer.SubscribeServiceStatus with unsupported parameter or return types

// skipped method CommandServer.SubscribeStatus with unsupported parameter or return types

// skipped method CommandServer.SubscribeTailscaleStatus with unsupported parameter or return types

// skipped method CommandServer.SubscribeUSBIPServerStatus with unsupported parameter or return types

// skipped method CommandServer.TailscaleLogout with unsupported parameter or return types

// skipped method CommandServer.URLTest with unsupported parameter or return types

- (void)updateWIFIState;
- (void)wake;
- (void)writeMessage:(int32_t)level message:(NSString* _Nullable)message;
@end

@interface LibboxConnection : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setID:) NSString* _Nonnull id_;
@property (nonatomic, setter=setInbound:) NSString* _Nonnull inbound;
@property (nonatomic, setter=setInboundType:) NSString* _Nonnull inboundType;
@property (nonatomic, setter=setIPVersion:) int32_t ipVersion;
@property (nonatomic, setter=setNetwork:) NSString* _Nonnull network;
@property (nonatomic, setter=setSource:) NSString* _Nonnull source;
@property (nonatomic, setter=setDestination:) NSString* _Nonnull destination;
@property (nonatomic, setter=setDomain:) NSString* _Nonnull domain;
@property (nonatomic, setter=setProtocol:) NSString* _Nonnull protocol;
@property (nonatomic, setter=setUser:) NSString* _Nonnull user;
@property (nonatomic, setter=setFromOutbound:) NSString* _Nonnull fromOutbound;
@property (nonatomic, setter=setCreatedAt:) int64_t createdAt;
@property (nonatomic, setter=setClosedAt:) int64_t closedAt;
@property (nonatomic, setter=setUplink:) int64_t uplink;
@property (nonatomic, setter=setDownlink:) int64_t downlink;
@property (nonatomic, setter=setUplinkTotal:) int64_t uplinkTotal;
@property (nonatomic, setter=setDownlinkTotal:) int64_t downlinkTotal;
@property (nonatomic, setter=setRule:) NSString* _Nonnull rule;
@property (nonatomic, setter=setOutbound:) NSString* _Nonnull outbound;
@property (nonatomic, setter=setOutboundType:) NSString* _Nonnull outboundType;
@property (nonatomic, setter=setProcessInfo:) LibboxProcessInfo* _Nullable processInfo;
- (id<LibboxStringIterator> _Nullable)chain;
- (NSString* _Nonnull)displayDestination;
@end

@interface LibboxConnectionEvent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setType:) int32_t type;
@property (nonatomic, setter=setID:) NSString* _Nonnull id_;
@property (nonatomic, setter=setConnection:) LibboxConnection* _Nullable connection;
@property (nonatomic, setter=setUplinkDelta:) int64_t uplinkDelta;
@property (nonatomic, setter=setDownlinkDelta:) int64_t downlinkDelta;
@property (nonatomic, setter=setClosedAt:) int64_t closedAt;
@end

@interface LibboxConnectionEvents : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setReset:) BOOL reset;
- (id<LibboxConnectionEventIterator> _Nullable)iterator;
@end

@interface LibboxConnectionOwner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setUserId:) int32_t userId;
@property (nonatomic, setter=setUserName:) NSString* _Nonnull userName;
@property (nonatomic, setter=setProcessPath:) NSString* _Nonnull processPath;
- (id<LibboxStringIterator> _Nullable)androidPackageNames;
- (void)setAndroidPackageNames:(id<LibboxStringIterator> _Nullable)names;
@end

@interface LibboxConnections : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (void)applyEvents:(LibboxConnectionEvents* _Nullable)events;
- (void)filterState:(int32_t)state;
- (id<LibboxConnectionIterator> _Nullable)iterator;
- (void)sortByDate;
- (void)sortByTraffic;
- (void)sortByTrafficTotal;
@end

@interface LibboxDeprecatedNote : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setDescription:) NSString* _Nonnull description;
@property (nonatomic, setter=setDeprecatedVersion:) NSString* _Nonnull deprecatedVersion;
@property (nonatomic, setter=setScheduledVersion:) NSString* _Nonnull scheduledVersion;
@property (nonatomic, setter=setEnvName:) NSString* _Nonnull envName;
@property (nonatomic, setter=setMigrationLink:) NSString* _Nonnull migrationLink;
- (BOOL)impending;
- (NSString* _Nonnull)message;
- (NSString* _Nonnull)messageWithLink;
@end

@interface LibboxErrorMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setMessage:) NSString* _Nonnull message;
- (NSData* _Nullable)encode;
@end

@interface LibboxExchangeContext : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)errnoCode:(int32_t)code;
- (void)errorCode:(int32_t)code;
- (void)onCancel:(id<LibboxFunc> _Nullable)callback;
- (void)rawSuccess:(NSData* _Nullable)result;
- (void)success:(NSString* _Nullable)result;
@end

@interface LibboxFDroidMirror : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setURL:) NSString* _Nonnull url;
@property (nonatomic, setter=setCountry:) NSString* _Nonnull country;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@end

@interface LibboxFDroidPingResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setURL:) NSString* _Nonnull url;
@property (nonatomic, setter=setLatencyMs:) int32_t latencyMs;
@property (nonatomic, setter=setError:) NSString* _Nonnull error;
@end

@interface LibboxFDroidUpdateInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setVersionCode:) int32_t versionCode;
@property (nonatomic, setter=setVersionName:) NSString* _Nonnull versionName;
@property (nonatomic, setter=setDownloadURL:) NSString* _Nonnull downloadURL;
@property (nonatomic, setter=setFileSize:) int64_t fileSize;
@property (nonatomic, setter=setFileSHA256:) NSString* _Nonnull fileSHA256;
@end

@interface LibboxImportRemoteProfile : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setURL:) NSString* _Nonnull url;
@property (nonatomic, setter=setHost:) NSString* _Nonnull host;
@end

@interface LibboxLogEntry : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setLevel:) int32_t level;
@property (nonatomic, setter=setMessage:) NSString* _Nonnull message;
@end

@interface LibboxNeighborEntry : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setAddress:) NSString* _Nonnull address;
@property (nonatomic, setter=setMacAddress:) NSString* _Nonnull macAddress;
@property (nonatomic, setter=setHostname:) NSString* _Nonnull hostname;
@end

@interface LibboxNeighborSubscription : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)close;
@end

@interface LibboxNetworkInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setIndex:) int32_t index;
@property (nonatomic, setter=setMTU:) int32_t mtu;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setAddresses:) id<LibboxStringIterator> _Nullable addresses;
@property (nonatomic, setter=setFlags:) int32_t flags;
@property (nonatomic, setter=setType:) int32_t type;
@property (nonatomic, setter=setDNSServer:) id<LibboxStringIterator> _Nullable dnsServer;
@property (nonatomic, setter=setMetered:) BOOL metered;
@end

@interface LibboxNetworkQualityProgress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setPhase:) int32_t phase;
@property (nonatomic, setter=setDownloadCapacity:) int64_t downloadCapacity;
@property (nonatomic, setter=setUploadCapacity:) int64_t uploadCapacity;
@property (nonatomic, setter=setDownloadRPM:) int32_t downloadRPM;
@property (nonatomic, setter=setUploadRPM:) int32_t uploadRPM;
@property (nonatomic, setter=setIdleLatencyMs:) int32_t idleLatencyMs;
@property (nonatomic, setter=setElapsedMs:) int64_t elapsedMs;
@property (nonatomic, setter=setDownloadCapacityAccuracy:) int32_t downloadCapacityAccuracy;
@property (nonatomic, setter=setUploadCapacityAccuracy:) int32_t uploadCapacityAccuracy;
@property (nonatomic, setter=setDownloadRPMAccuracy:) int32_t downloadRPMAccuracy;
@property (nonatomic, setter=setUploadRPMAccuracy:) int32_t uploadRPMAccuracy;
@end

@interface LibboxNetworkQualityResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setDownloadCapacity:) int64_t downloadCapacity;
@property (nonatomic, setter=setUploadCapacity:) int64_t uploadCapacity;
@property (nonatomic, setter=setDownloadRPM:) int32_t downloadRPM;
@property (nonatomic, setter=setUploadRPM:) int32_t uploadRPM;
@property (nonatomic, setter=setIdleLatencyMs:) int32_t idleLatencyMs;
@property (nonatomic, setter=setDownloadCapacityAccuracy:) int32_t downloadCapacityAccuracy;
@property (nonatomic, setter=setUploadCapacityAccuracy:) int32_t uploadCapacityAccuracy;
@property (nonatomic, setter=setDownloadRPMAccuracy:) int32_t downloadRPMAccuracy;
@property (nonatomic, setter=setUploadRPMAccuracy:) int32_t uploadRPMAccuracy;
@end

@interface LibboxNetworkQualityTest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (void)cancel;
- (void)start:(NSString* _Nullable)configURL serial:(BOOL)serial maxRuntimeSeconds:(int32_t)maxRuntimeSeconds http3:(BOOL)http3 handler:(id<LibboxNetworkQualityTestHandler> _Nullable)handler;
@end

@interface LibboxNetworkQualityTestSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxNotification : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setIdentifier:) NSString* _Nonnull identifier;
@property (nonatomic, setter=setTypeName:) NSString* _Nonnull typeName;
@property (nonatomic, setter=setTypeID:) int32_t typeID;
@property (nonatomic, setter=setTitle:) NSString* _Nonnull title;
@property (nonatomic, setter=setSubtitle:) NSString* _Nonnull subtitle;
@property (nonatomic, setter=setBody:) NSString* _Nonnull body;
@property (nonatomic, setter=setOpenURL:) NSString* _Nonnull openURL;
@end

@interface LibboxOutboundGroup : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setTag:) NSString* _Nonnull tag;
@property (nonatomic, setter=setType:) NSString* _Nonnull type;
@property (nonatomic, setter=setSelectable:) BOOL selectable;
@property (nonatomic, setter=setSelected:) NSString* _Nonnull selected;
@property (nonatomic, setter=setIsExpand:) BOOL isExpand;
- (id<LibboxOutboundGroupItemIterator> _Nullable)getItems;
@end

@interface LibboxOutboundGroupItem : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setTag:) NSString* _Nonnull tag;
@property (nonatomic, setter=setType:) NSString* _Nonnull type;
@property (nonatomic, setter=setURLTestTime:) int64_t urlTestTime;
@property (nonatomic, setter=setURLTestDelay:) int32_t urlTestDelay;
@end

@interface LibboxOverrideOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setAutoRedirect:) BOOL autoRedirect;
@property (nonatomic, setter=setIncludePackage:) id<LibboxStringIterator> _Nullable includePackage;
@property (nonatomic, setter=setExcludePackage:) id<LibboxStringIterator> _Nullable excludePackage;
@end

@interface LibboxPProfServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)port;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxPlatformUser : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setUsername:) NSString* _Nonnull username;
@property (nonatomic, setter=setUid:) int32_t uid;
@property (nonatomic, setter=setGid:) int32_t gid;
@property (nonatomic, setter=setHomeDir:) NSString* _Nonnull homeDir;
@property (nonatomic, setter=setShell:) NSString* _Nonnull shell;
- (id<LibboxInt32Iterator> _Nullable)groups;
- (void)setGroups:(id<LibboxInt32Iterator> _Nullable)groups;
@end

@interface LibboxProcessInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setProcessID:) int64_t processID;
@property (nonatomic, setter=setUserID:) int32_t userID;
@property (nonatomic, setter=setUserName:) NSString* _Nonnull userName;
@property (nonatomic, setter=setProcessPath:) NSString* _Nonnull processPath;
- (id<LibboxStringIterator> _Nullable)packageNames;
@end

@interface LibboxProfileContent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setType:) int32_t type;
@property (nonatomic, setter=setConfig:) NSString* _Nonnull config;
@property (nonatomic, setter=setRemotePath:) NSString* _Nonnull remotePath;
@property (nonatomic, setter=setAutoUpdate:) BOOL autoUpdate;
@property (nonatomic, setter=setAutoUpdateInterval:) int32_t autoUpdateInterval;
@property (nonatomic, setter=setLastUpdated:) int64_t lastUpdated;
- (NSData* _Nullable)encode;
@end

@interface LibboxProfileContentRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setProfileID:) int64_t profileID;
- (NSData* _Nullable)encode;
@end

@interface LibboxProfileDecoder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)decode:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxProfilePreviewIterator> _Nullable)iterator;
@end

@interface LibboxProfileEncoder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)append:(LibboxProfilePreview* _Nullable)profile;
- (NSData* _Nullable)encode;
@end

@interface LibboxProfilePreview : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setProfileID:) int64_t profileID;
@property (nonatomic, setter=setName:) NSString* _Nonnull name;
@property (nonatomic, setter=setType:) int32_t type;
@end

@interface LibboxRemoteConnectionOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setURL:) NSString* _Nonnull url;
@property (nonatomic, setter=setSecret:) NSString* _Nonnull secret;
@end

@interface LibboxRoutePrefix : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)address;
- (NSString* _Nonnull)mask;
- (int32_t)prefix;
- (NSString* _Nonnull)string;
@end

@interface LibboxSTUNTest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (void)cancel;
- (void)start:(NSString* _Nullable)server handler:(id<LibboxSTUNTestHandler> _Nullable)handler;
@end

@interface LibboxSTUNTestProgress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setPhase:) int32_t phase;
@property (nonatomic, setter=setExternalAddr:) NSString* _Nonnull externalAddr;
@property (nonatomic, setter=setLatencyMs:) int32_t latencyMs;
@property (nonatomic, setter=setNATMapping:) int32_t natMapping;
@property (nonatomic, setter=setNATFiltering:) int32_t natFiltering;
@end

@interface LibboxSTUNTestResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setExternalAddr:) NSString* _Nonnull externalAddr;
@property (nonatomic, setter=setLatencyMs:) int32_t latencyMs;
@property (nonatomic, setter=setNATMapping:) int32_t natMapping;
@property (nonatomic, setter=setNATFiltering:) int32_t natFiltering;
@property (nonatomic, setter=setNATTypeSupported:) BOOL natTypeSupported;
@end

@interface LibboxSTUNTestSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxSetupOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setBasePath:) NSString* _Nonnull basePath;
@property (nonatomic, setter=setWorkingPath:) NSString* _Nonnull workingPath;
@property (nonatomic, setter=setTempPath:) NSString* _Nonnull tempPath;
@property (nonatomic, setter=setFixAndroidStack:) BOOL fixAndroidStack;
@property (nonatomic, setter=setCommandServerListenPort:) int32_t commandServerListenPort;
@property (nonatomic, setter=setCommandServerSecret:) NSString* _Nonnull commandServerSecret;
@property (nonatomic, setter=setLogMaxLines:) long logMaxLines;
@property (nonatomic, setter=setDebug:) BOOL debug;
@property (nonatomic, setter=setCrashReportSource:) NSString* _Nonnull crashReportSource;
@property (nonatomic, setter=setOomKillerEnabled:) BOOL oomKillerEnabled;
@property (nonatomic, setter=setOomKillerDisabled:) BOOL oomKillerDisabled;
@property (nonatomic, setter=setOomMemoryLimit:) int64_t oomMemoryLimit;
@end

@interface LibboxStatusMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setMemory:) int64_t memory;
@property (nonatomic, setter=setGoroutines:) int32_t goroutines;
@property (nonatomic, setter=setConnectionsIn:) int32_t connectionsIn;
@property (nonatomic, setter=setConnectionsOut:) int32_t connectionsOut;
@property (nonatomic, setter=setTrafficAvailable:) BOOL trafficAvailable;
@property (nonatomic, setter=setUplink:) int64_t uplink;
@property (nonatomic, setter=setDownlink:) int64_t downlink;
@property (nonatomic, setter=setUplinkTotal:) int64_t uplinkTotal;
@property (nonatomic, setter=setDownlinkTotal:) int64_t downlinkTotal;
@end

@interface LibboxStringBox : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setValue:) NSString* _Nonnull value;
@end

@interface LibboxSystemProxyStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setAvailable:) BOOL available;
@property (nonatomic, setter=setEnabled:) BOOL enabled;
@end

@interface LibboxTailscaleEndpointStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setEndpointTag:) NSString* _Nonnull endpointTag;
@property (nonatomic, setter=setBackendState:) NSString* _Nonnull backendState;
@property (nonatomic, setter=setAuthURL:) NSString* _Nonnull authURL;
@property (nonatomic, setter=setNetworkName:) NSString* _Nonnull networkName;
@property (nonatomic, setter=setMagicDNSSuffix:) NSString* _Nonnull magicDNSSuffix;
@property (nonatomic, setter=setSelf:) LibboxTailscalePeer* _Nullable self_;
@property (nonatomic, setter=setExitNode:) LibboxTailscalePeer* _Nullable exitNode;
@property (nonatomic, setter=setKeyAuth:) BOOL keyAuth;
- (id<LibboxTailscaleUserGroupIterator> _Nullable)userGroups;
@end

@interface LibboxTailscalePeer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setStableID:) NSString* _Nonnull stableID;
@property (nonatomic, setter=setHostName:) NSString* _Nonnull hostName;
@property (nonatomic, setter=setDNSName:) NSString* _Nonnull dnsName;
@property (nonatomic, setter=setOS:) NSString* _Nonnull os;
@property (nonatomic, setter=setOnline:) BOOL online;
@property (nonatomic, setter=setExitNode:) BOOL exitNode;
@property (nonatomic, setter=setExitNodeOption:) BOOL exitNodeOption;
@property (nonatomic, setter=setShareeNode:) BOOL shareeNode;
@property (nonatomic, setter=setExpired:) BOOL expired;
@property (nonatomic, setter=setActive:) BOOL active;
@property (nonatomic, setter=setRxBytes:) int64_t rxBytes;
@property (nonatomic, setter=setTxBytes:) int64_t txBytes;
@property (nonatomic, setter=setKeyExpiry:) int64_t keyExpiry;
@property (nonatomic, setter=setLastSeen:) int64_t lastSeen;
- (id<LibboxStringIterator> _Nullable)sshHostKeys;
- (id<LibboxStringIterator> _Nullable)tailscaleIPs;
@end

@interface LibboxTailscalePingResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setLatencyMs:) double latencyMs;
@property (nonatomic, setter=setIsDirect:) BOOL isDirect;
@property (nonatomic, setter=setEndpoint:) NSString* _Nonnull endpoint;
@property (nonatomic, setter=setDERPRegionID:) int32_t derpRegionID;
@property (nonatomic, setter=setDERPRegionCode:) NSString* _Nonnull derpRegionCode;
@property (nonatomic, setter=setError:) NSString* _Nonnull error;
@end

@interface LibboxTailscalePingSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxTailscaleSSHOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setEndpointTag:) NSString* _Nonnull endpointTag;
@property (nonatomic, setter=setPeerAddress:) NSString* _Nonnull peerAddress;
@property (nonatomic, setter=setUsername:) NSString* _Nonnull username;
@property (nonatomic, setter=setTerminalType:) NSString* _Nonnull terminalType;
@property (nonatomic, setter=setColumns:) int32_t columns;
@property (nonatomic, setter=setRows:) int32_t rows;
@property (nonatomic, setter=setWidthPixels:) int32_t widthPixels;
@property (nonatomic, setter=setHeightPixels:) int32_t heightPixels;
@property (nonatomic, setter=setHostKeys:) id<LibboxStringIterator> _Nullable hostKeys;
@property (nonatomic, setter=setForwardAgent:) BOOL forwardAgent;
@end

@interface LibboxTailscaleSSHSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)sendInput:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
- (BOOL)sendResize:(int32_t)columns rows:(int32_t)rows widthPixels:(int32_t)widthPixels heightPixels:(int32_t)heightPixels error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxTailscaleStatusSubscription : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxTailscaleStatusUpdate : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (id<LibboxTailscaleEndpointStatusIterator> _Nullable)endpoints;
@end

@interface LibboxTailscaleUserGroup : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setUserID:) int64_t userID;
@property (nonatomic, setter=setLoginName:) NSString* _Nonnull loginName;
@property (nonatomic, setter=setDisplayName:) NSString* _Nonnull displayName;
@property (nonatomic, setter=setProfilePicURL:) NSString* _Nonnull profilePicURL;
- (id<LibboxTailscalePeerIterator> _Nullable)peers;
@end

@interface LibboxUSBDeviceDescriptor : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)serverTag deviceID:(NSString* _Nullable)deviceID;
@property (nonatomic, setter=setServerTag:) NSString* _Nonnull serverTag;
@property (nonatomic, setter=setDeviceID:) NSString* _Nonnull deviceID;
@property (nonatomic, setter=setBusNum:) int32_t busNum;
@property (nonatomic, setter=setDevNum:) int32_t devNum;
@property (nonatomic, setter=setSpeed:) int32_t speed;
@property (nonatomic, setter=setVendorID:) int32_t vendorID;
@property (nonatomic, setter=setProductID:) int32_t productID;
@property (nonatomic, setter=setBCDDevice:) int32_t bcdDevice;
@property (nonatomic, setter=setDeviceClass:) int32_t deviceClass;
@property (nonatomic, setter=setDeviceSubClass:) int32_t deviceSubClass;
@property (nonatomic, setter=setDeviceProtocol:) int32_t deviceProtocol;
@property (nonatomic, setter=setConfigurationValue:) int32_t configurationValue;
@property (nonatomic, setter=setNumConfigurations:) int32_t numConfigurations;
@property (nonatomic, setter=setSerial:) NSString* _Nonnull serial;
@property (nonatomic, setter=setProduct:) NSString* _Nonnull product;
- (void)addInterface:(int32_t)interfaceClass interfaceSubClass:(int32_t)interfaceSubClass interfaceProtocol:(int32_t)interfaceProtocol;
@end

@interface LibboxUSBIPServerStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setServerTag:) NSString* _Nonnull serverTag;
- (id<LibboxUSBSharedDeviceIterator> _Nullable)devices;
@end

@interface LibboxUSBIPServerStatusSubscription : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxUSBIPServerStatusUpdate : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (id<LibboxUSBIPServerStatusIterator> _Nullable)servers;
@end

@interface LibboxUSBIsoPacket : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setOffset:) int32_t offset;
@property (nonatomic, setter=setLength:) int32_t length;
@property (nonatomic, setter=setActualLength:) int32_t actualLength;
@property (nonatomic, setter=setStatus:) int32_t status;
@end

@interface LibboxUSBLocalDeviceInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setStableID:) NSString* _Nonnull stableID;
@property (nonatomic, setter=setBusID:) NSString* _Nonnull busID;
@property (nonatomic, setter=setBackend:) int32_t backend;
@property (nonatomic, setter=setBusNum:) int32_t busNum;
@property (nonatomic, setter=setDevNum:) int32_t devNum;
@property (nonatomic, setter=setSpeed:) int32_t speed;
@property (nonatomic, setter=setVendorID:) int32_t vendorID;
@property (nonatomic, setter=setProductID:) int32_t productID;
@property (nonatomic, setter=setBCDDevice:) int32_t bcdDevice;
@property (nonatomic, setter=setDeviceClass:) int32_t deviceClass;
@property (nonatomic, setter=setDeviceSubClass:) int32_t deviceSubClass;
@property (nonatomic, setter=setDeviceProtocol:) int32_t deviceProtocol;
@property (nonatomic, setter=setConfigurationValue:) int32_t configurationValue;
@property (nonatomic, setter=setNumConfigurations:) int32_t numConfigurations;
@property (nonatomic, setter=setSerial:) NSString* _Nonnull serial;
@property (nonatomic, setter=setProduct:) NSString* _Nonnull product;
- (id<LibboxUSBSharedDeviceInterfaceIterator> _Nullable)interfaces;
@end

@interface LibboxUSBLocalProvidedDevice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setServerTag:) NSString* _Nonnull serverTag;
@property (nonatomic, setter=setDeviceID:) NSString* _Nonnull deviceID;
@property (nonatomic, setter=setLocalDeviceID:) NSString* _Nonnull localDeviceID;
@property (nonatomic, setter=setLabel:) NSString* _Nonnull label;
@property (nonatomic, setter=setVendorID:) int32_t vendorID;
@property (nonatomic, setter=setProductID:) int32_t productID;
@end

@interface LibboxUSBLocalProviderManager : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (LibboxUSBLocalProvidedDevice* _Nullable)attach:(NSString* _Nullable)serverTag localDeviceID:(NSString* _Nullable)localDeviceID error:(NSError* _Nullable* _Nullable)error;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)detach:(NSString* _Nullable)deviceID error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxUSBLocalDeviceInfoIterator> _Nullable)listDevices:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxUSBProviderSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)attachDevice:(LibboxUSBDeviceDescriptor* _Nullable)descriptor error:(NSError* _Nullable* _Nullable)error;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)detachDevice:(NSString* _Nullable)deviceID error:(NSError* _Nullable* _Nullable)error;
- (BOOL)sendURBResponse:(LibboxUSBURBResponse* _Nullable)response error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxUSBSharedDevice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setBusID:) NSString* _Nonnull busID;
@property (nonatomic, setter=setStableID:) NSString* _Nonnull stableID;
@property (nonatomic, setter=setBackend:) int32_t backend;
@property (nonatomic, setter=setState:) int32_t state;
@property (nonatomic, setter=setDeviceID:) NSString* _Nonnull deviceID;
@property (nonatomic, setter=setBusNum:) int32_t busNum;
@property (nonatomic, setter=setDevNum:) int32_t devNum;
@property (nonatomic, setter=setSpeed:) int32_t speed;
@property (nonatomic, setter=setVendorID:) int32_t vendorID;
@property (nonatomic, setter=setProductID:) int32_t productID;
@property (nonatomic, setter=setBCDDevice:) int32_t bcdDevice;
@property (nonatomic, setter=setDeviceClass:) int32_t deviceClass;
@property (nonatomic, setter=setDeviceSubClass:) int32_t deviceSubClass;
@property (nonatomic, setter=setDeviceProtocol:) int32_t deviceProtocol;
@property (nonatomic, setter=setConfigurationValue:) int32_t configurationValue;
@property (nonatomic, setter=setNumConfigurations:) int32_t numConfigurations;
@property (nonatomic, setter=setSerial:) NSString* _Nonnull serial;
@property (nonatomic, setter=setProduct:) NSString* _Nonnull product;
- (id<LibboxUSBSharedDeviceInterfaceIterator> _Nullable)interfaces;
@end

@interface LibboxUSBSharedDeviceInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setInterfaceClass:) int32_t interfaceClass;
@property (nonatomic, setter=setInterfaceSubClass:) int32_t interfaceSubClass;
@property (nonatomic, setter=setInterfaceProtocol:) int32_t interfaceProtocol;
@end

@interface LibboxUSBURBRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic, setter=setDeviceID:) NSString* _Nonnull deviceID;
@property (nonatomic, setter=setSeq:) int64_t seq;
@property (nonatomic, setter=setEndpoint:) int32_t endpoint;
@property (nonatomic, setter=setDirectionIn:) BOOL directionIn;
@property (nonatomic, setter=setTransferFlags:) int32_t transferFlags;
@property (nonatomic, setter=setSetup:) NSData* _Nullable setup;
@property (nonatomic, setter=setTransferBufferLength:) int32_t transferBufferLength;
@property (nonatomic, setter=setOutData:) NSData* _Nullable outData;
@property (nonatomic, setter=setNumberOfPackets:) int32_t numberOfPackets;
@property (nonatomic, setter=setStartFrame:) int32_t startFrame;
@property (nonatomic, setter=setInterval:) int32_t interval;
- (LibboxUSBIsoPacket* _Nullable)getIsoPacket:(int32_t)index;
- (int32_t)isoPacketCount;
@end

@interface LibboxUSBURBResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)deviceID seq:(int64_t)seq;
@property (nonatomic, setter=setDeviceID:) NSString* _Nonnull deviceID;
@property (nonatomic, setter=setSeq:) int64_t seq;
@property (nonatomic, setter=setStatus:) int32_t status;
@property (nonatomic, setter=setActualLength:) int32_t actualLength;
@property (nonatomic, setter=setInData:) NSData* _Nullable inData;
- (void)addIsoPacket:(int32_t)offset length:(int32_t)length actualLength:(int32_t)actualLength status:(int32_t)status;
@end

@interface LibboxWIFIState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)wifiSSID wifiBSSID:(NSString* _Nullable)wifiBSSID;
@property (nonatomic, setter=setSSID:) NSString* _Nonnull ssid;
@property (nonatomic, setter=setBSSID:) NSString* _Nonnull bssid;
@end

FOUNDATION_EXPORT const int32_t LibboxCommandClashMode;
FOUNDATION_EXPORT const int32_t LibboxCommandConnections;
FOUNDATION_EXPORT const int32_t LibboxCommandGroup;
FOUNDATION_EXPORT const int32_t LibboxCommandLog;
FOUNDATION_EXPORT const int32_t LibboxCommandOutbounds;
FOUNDATION_EXPORT const int32_t LibboxCommandStatus;
FOUNDATION_EXPORT const int64_t LibboxConnectionEventClosed;
FOUNDATION_EXPORT const int64_t LibboxConnectionEventNew;
FOUNDATION_EXPORT const int64_t LibboxConnectionEventUpdate;
FOUNDATION_EXPORT const int64_t LibboxConnectionStateActive;
FOUNDATION_EXPORT const int64_t LibboxConnectionStateAll;
FOUNDATION_EXPORT const int64_t LibboxConnectionStateClosed;
FOUNDATION_EXPORT NSString* _Nonnull const LibboxDNSModeDisabled;
FOUNDATION_EXPORT NSString* _Nonnull const LibboxDNSModeHijack;
FOUNDATION_EXPORT NSString* _Nonnull const LibboxDNSModeNative;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeCellular;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeEthernet;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeOther;
FOUNDATION_EXPORT const int32_t LibboxInterfaceTypeWIFI;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeError;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeProfileContent;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeProfileContentRequest;
FOUNDATION_EXPORT const int64_t LibboxMessageTypeProfileList;
FOUNDATION_EXPORT const int32_t LibboxNATFilteringAddressAndPortDependent;
FOUNDATION_EXPORT const int32_t LibboxNATFilteringAddressDependent;
FOUNDATION_EXPORT const int32_t LibboxNATFilteringEndpointIndependent;
FOUNDATION_EXPORT const int32_t LibboxNATMappingAddressAndPortDependent;
FOUNDATION_EXPORT const int32_t LibboxNATMappingAddressDependent;
FOUNDATION_EXPORT const int32_t LibboxNATMappingEndpointIndependent;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityAccuracyHigh;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityAccuracyLow;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityAccuracyMedium;
FOUNDATION_EXPORT NSString* _Nonnull const LibboxNetworkQualityDefaultConfigURL;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityDefaultMaxRuntimeSeconds;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityPhaseDone;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityPhaseDownload;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityPhaseIdle;
FOUNDATION_EXPORT const int32_t LibboxNetworkQualityPhaseUpload;
FOUNDATION_EXPORT const int32_t LibboxProfileTypeLocal;
FOUNDATION_EXPORT const int32_t LibboxProfileTypeRemote;
FOUNDATION_EXPORT const int32_t LibboxProfileTypeiCloud;
FOUNDATION_EXPORT NSString* _Nonnull const LibboxSTUNDefaultServer;
FOUNDATION_EXPORT const int32_t LibboxSTUNPhaseBinding;
FOUNDATION_EXPORT const int32_t LibboxSTUNPhaseDone;
FOUNDATION_EXPORT const int32_t LibboxSTUNPhaseNATFiltering;
FOUNDATION_EXPORT const int32_t LibboxSTUNPhaseNATMapping;
FOUNDATION_EXPORT const int32_t LibboxUSBBackendDarwinIOKit;
FOUNDATION_EXPORT const int32_t LibboxUSBBackendDynamic;
FOUNDATION_EXPORT const int32_t LibboxUSBBackendLinuxSysfs;
FOUNDATION_EXPORT const int32_t LibboxUSBBackendUnspecified;
FOUNDATION_EXPORT const int32_t LibboxUSBBackendWindowsVBoxUSB;
FOUNDATION_EXPORT const int32_t LibboxUSBDeviceStateAttached;
FOUNDATION_EXPORT const int32_t LibboxUSBDeviceStateIdle;
FOUNDATION_EXPORT const int32_t LibboxUSBDeviceStateUnavailable;

FOUNDATION_EXPORT BOOL LibboxAvailablePort(int32_t startPort, int32_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL LibboxCheckConfig(NSString* _Nullable configContent, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxFDroidUpdateInfo* _Nullable LibboxCheckFDroidUpdate(NSString* _Nullable mirrorURL, NSString* _Nullable packageName, int32_t currentVersionCode, NSString* _Nullable cachePath, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL LibboxCompareSemver(NSString* _Nullable left, NSString* _Nullable right);

FOUNDATION_EXPORT BOOL LibboxCreateZipArchive(NSString* _Nullable sourcePath, NSString* _Nullable destinationPath, BOOL encrypt, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxErrorMessage* _Nullable LibboxDecodeErrorMessage(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT int32_t LibboxDecodeLengthChunk(NSData* _Nullable data);

FOUNDATION_EXPORT LibboxProfileContent* _Nullable LibboxDecodeProfileContent(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxProfileContentRequest* _Nullable LibboxDecodeProfileContentRequest(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable LibboxEncodeChunkedMessage(NSData* _Nullable data);

FOUNDATION_EXPORT LibboxConnectionOwner* _Nullable LibboxFindConnectionOwner(int32_t ipProtocol, NSString* _Nullable sourceAddress, int32_t sourcePort, NSString* _Nullable destinationAddress, int32_t destinationPort, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatBitrate(int64_t bps);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatBytes(int64_t length);

FOUNDATION_EXPORT LibboxStringBox* _Nullable LibboxFormatConfig(NSString* _Nullable configContent, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatDuration(int64_t duration);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatFQDN(NSString* _Nullable fqdn);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatMemoryBytes(int64_t length);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatNATFiltering(int32_t value);

FOUNDATION_EXPORT NSString* _Nonnull LibboxFormatNATMapping(int32_t value);

FOUNDATION_EXPORT NSString* _Nonnull LibboxGenerateRemoteProfileImportLink(NSString* _Nullable name, NSString* _Nullable remoteURL);

FOUNDATION_EXPORT id<LibboxFDroidMirrorIterator> _Nullable LibboxGetFDroidMirrors(void);

FOUNDATION_EXPORT int32_t LibboxGetTunnelFileDescriptor(void);

FOUNDATION_EXPORT NSString* _Nonnull LibboxGoVersion(void);

FOUNDATION_EXPORT id<LibboxBridgeSession> _Nullable LibboxNewBridgeService(LibboxBridgeOptions* _Nullable options, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxCommandClient* _Nullable LibboxNewCommandClient(id<LibboxCommandClientHandler> _Nullable handler, LibboxCommandClientOptions* _Nullable options);

FOUNDATION_EXPORT LibboxCommandServer* _Nullable LibboxNewCommandServer(id<LibboxCommandServerHandler> _Nullable handler, id<LibboxPlatformInterface> _Nullable platformInterface, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxConnections* _Nullable LibboxNewConnections(void);

FOUNDATION_EXPORT id<LibboxHTTPClient> _Nullable LibboxNewHTTPClient(void);

FOUNDATION_EXPORT LibboxNetworkQualityTest* _Nullable LibboxNewNetworkQualityTest(void);

FOUNDATION_EXPORT LibboxPProfServer* _Nullable LibboxNewPProfServer(long port);

FOUNDATION_EXPORT LibboxCommandClient* _Nullable LibboxNewRemoteCommandClient(id<LibboxCommandClientHandler> _Nullable handler, LibboxCommandClientOptions* _Nullable options, LibboxRemoteConnectionOptions* _Nullable remoteOptions, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxSTUNTest* _Nullable LibboxNewSTUNTest(void);

FOUNDATION_EXPORT LibboxCommandClient* _Nullable LibboxNewStandaloneCommandClient(void);

FOUNDATION_EXPORT LibboxCommandClient* _Nullable LibboxNewStandaloneRemoteCommandClient(LibboxRemoteConnectionOptions* _Nullable remoteOptions, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxUSBDeviceDescriptor* _Nullable LibboxNewUSBDeviceDescriptor(NSString* _Nullable serverTag, NSString* _Nullable deviceID);

FOUNDATION_EXPORT LibboxUSBURBResponse* _Nullable LibboxNewUSBURBResponse(NSString* _Nullable deviceID, int64_t seq);

FOUNDATION_EXPORT LibboxWIFIState* _Nullable LibboxNewWIFIState(NSString* _Nullable wifiSSID, NSString* _Nullable wifiBSSID);

FOUNDATION_EXPORT id<LibboxShellSession> _Nullable LibboxOpenNativePipeSession(NSString* _Nullable shell, NSString* _Nullable cwd, id<LibboxStringIterator> _Nullable args, id<LibboxStringIterator> _Nullable environ, int32_t uid, int32_t gid, id<LibboxInt32Iterator> _Nullable groups, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT id<LibboxShellSession> _Nullable LibboxOpenNativeShellSession(NSString* _Nullable shell, NSString* _Nullable cwd, id<LibboxStringIterator> _Nullable args, id<LibboxStringIterator> _Nullable environ, NSString* _Nullable term, int32_t rows, int32_t cols, int32_t uid, int32_t gid, id<LibboxInt32Iterator> _Nullable groups, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxImportRemoteProfile* _Nullable LibboxParseRemoteProfileImportLink(NSString* _Nullable importLink, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxFDroidPingResult* _Nullable LibboxPingFDroidMirror(NSString* _Nullable mirrorURL);

FOUNDATION_EXPORT id<LibboxFDroidPingResultIterator> _Nullable LibboxPingFDroidMirrors(NSString* _Nullable mirrorURLs, NSError* _Nullable* _Nullable error);

/**
 * PrepareCrashSignalHandlers captures Go's original synchronous signal handlers.

In gomobile/c-archive embeddings, package init runs on the first Go entry.
That means a native crash reporter installed before the first Go call would
otherwise be captured as the "Go" handler and break handler restoration on
SIGSEGV. Go skips SIGTRAP in c-archive mode, so install its trap trampoline
before saving handlers. Call this before installing PLCrashReporter.
 */
FOUNDATION_EXPORT void LibboxPrepareCrashSignalHandlers(void);

FOUNDATION_EXPORT void LibboxPromoteOOMDraft(void);

FOUNDATION_EXPORT void LibboxPromoteOOMDraftAt(NSString* _Nullable workingPath);

FOUNDATION_EXPORT NSString* _Nonnull LibboxProxyDisplayType(NSString* _Nullable proxyType);

FOUNDATION_EXPORT LibboxStringBox* _Nullable LibboxRandomHex(int32_t length);

FOUNDATION_EXPORT id<LibboxNeighborEntryIterator> _Nullable LibboxReadBootpdLeases(void);

/**
 * ReinstallCrashSignalHandlers installs a combined signal handler that chains
PLCrashReporter (native crash report) and Go's runtime handler (Go crash log).

Call PrepareCrashSignalHandlers before installing PLCrashReporter, then call
this after PLCrashReporter has been installed.

Flow on SIGSEGV:
 1. Combined handler calls PLCrashReporter's saved handler → .plcrash written
 2. Combined handler restores Go's handler via sigaction
 3. Combined handler returns — kernel re-executes faulting instruction
 4. PLCrashReporter's pending raise() (SI_USER) is ignored by Go's handler
 5. Hardware fault → Go's handler → preparePanic → kernel sigreturn →
    sigpanic → crash output via debug.SetCrashOutput

Flow on SIGTRAP:
 1. PrepareCrashSignalHandlers force-installs Go's cgo trap trampoline
 2. Combined handler calls PLCrashReporter's saved handler → .plcrash written
 3. Combined handler directly calls the saved Go trap trampoline
 */
FOUNDATION_EXPORT void LibboxReinstallCrashSignalHandlers(void);

FOUNDATION_EXPORT void LibboxReloadSetupOptions(LibboxSetupOptions* _Nullable options);

FOUNDATION_EXPORT BOOL LibboxSetLocale(NSString* _Nullable localeId, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void LibboxSetXPCDialer(id<LibboxXPCDialer> _Nullable dialer);

FOUNDATION_EXPORT BOOL LibboxSetup(LibboxSetupOptions* _Nullable options, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT LibboxNeighborSubscription* _Nullable LibboxSubscribeNeighborTable(id<LibboxNeighborUpdateListener> _Nullable listener, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void LibboxTriggerGoPanic(void);

FOUNDATION_EXPORT NSString* _Nonnull LibboxVersion(void);

@class LibboxBridgeSession;

@class LibboxCommandClientHandler;

@class LibboxCommandServerHandler;

@class LibboxConnectionEventIterator;

@class LibboxConnectionIterator;

@class LibboxDeprecatedNoteIterator;

@class LibboxFDroidMirrorIterator;

@class LibboxFDroidPingResultIterator;

@class LibboxFunc;

@class LibboxHTTPClient;

@class LibboxHTTPRequest;

@class LibboxHTTPResponse;

@class LibboxHTTPResponseWriteToProgressHandler;

@class LibboxInt32Iterator;

@class LibboxInterfaceUpdateListener;

@class LibboxLocalDNSTransport;

@class LibboxLogIterator;

@class LibboxNeighborEntryIterator;

@class LibboxNeighborUpdateListener;

@class LibboxNetworkInterfaceIterator;

@class LibboxNetworkQualityTestHandler;

@class LibboxOnDemandRule;

@class LibboxOnDemandRuleIterator;

@class LibboxOutboundGroupItemIterator;

@class LibboxOutboundGroupIterator;

@class LibboxPlatformInterface;

@class LibboxProfilePreviewIterator;

@class LibboxRoutePrefixIterator;

@class LibboxSTUNTestHandler;

@class LibboxShellSession;

@class LibboxStringIterator;

@class LibboxTailscaleEndpointStatusIterator;

@class LibboxTailscalePeerIterator;

@class LibboxTailscalePingHandler;

@class LibboxTailscaleSSHHandler;

@class LibboxTailscaleStatusHandler;

@class LibboxTailscaleUserGroupIterator;

@class LibboxTunOptions;

@class LibboxUSBIPServerStatusHandler;

@class LibboxUSBIPServerStatusIterator;

@class LibboxUSBLocalDeviceInfoIterator;

@class LibboxUSBLocalProviderHandler;

@class LibboxUSBProviderHandler;

@class LibboxUSBSharedDeviceInterfaceIterator;

@class LibboxUSBSharedDeviceIterator;

@class LibboxXPCDialer;

@interface LibboxBridgeSession : NSObject <goSeqRefInterface, LibboxBridgeSession> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (int32_t)fileDescriptor;
- (BOOL)inet6Active;
- (NSString* _Nonnull)name;
- (BOOL)setEgress:(NSString* _Nullable)interfaceName error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxCommandClientHandler : NSObject <goSeqRefInterface, LibboxCommandClientHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)clearLogs;
- (void)connected;
- (void)disconnected:(NSString* _Nullable)message;
- (void)initializeClashMode:(id<LibboxStringIterator> _Nullable)modeList currentMode:(NSString* _Nullable)currentMode;
- (void)setDefaultLogLevel:(int32_t)level;
- (void)updateClashMode:(NSString* _Nullable)newMode;
- (void)writeConnectionEvents:(LibboxConnectionEvents* _Nullable)events;
- (void)writeGroups:(id<LibboxOutboundGroupIterator> _Nullable)message;
- (void)writeLogs:(id<LibboxLogIterator> _Nullable)messageList;
- (void)writeOutbounds:(id<LibboxOutboundGroupItemIterator> _Nullable)message;
- (void)writeStatus:(LibboxStatusMessage* _Nullable)message;
@end

@interface LibboxCommandServerHandler : NSObject <goSeqRefInterface, LibboxCommandServerHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)connectSSHAgent:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (LibboxSystemProxyStatus* _Nullable)getSystemProxyStatus:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceReload:(NSError* _Nullable* _Nullable)error;
- (BOOL)serviceStop:(NSError* _Nullable* _Nullable)error;
- (BOOL)setSystemProxyEnabled:(BOOL)enabled error:(NSError* _Nullable* _Nullable)error;
- (BOOL)triggerNativeCrash:(NSError* _Nullable* _Nullable)error;
- (void)writeDebugMessage:(NSString* _Nullable)message;
@end

@interface LibboxConnectionEventIterator : NSObject <goSeqRefInterface, LibboxConnectionEventIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxConnectionEvent* _Nullable)next;
@end

@interface LibboxConnectionIterator : NSObject <goSeqRefInterface, LibboxConnectionIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxConnection* _Nullable)next;
@end

@interface LibboxDeprecatedNoteIterator : NSObject <goSeqRefInterface, LibboxDeprecatedNoteIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxDeprecatedNote* _Nullable)next;
@end

@interface LibboxFDroidMirrorIterator : NSObject <goSeqRefInterface, LibboxFDroidMirrorIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidMirror* _Nullable)next;
@end

@interface LibboxFDroidPingResultIterator : NSObject <goSeqRefInterface, LibboxFDroidPingResultIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxFDroidPingResult* _Nullable)next;
@end

@interface LibboxFunc : NSObject <goSeqRefInterface, LibboxFunc> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)invoke:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxHTTPClient : NSObject <goSeqRefInterface, LibboxHTTPClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)close;
- (void)keepAlive;
- (void)modernTLS;
- (id<LibboxHTTPRequest> _Nullable)newRequest;
- (void)pinnedSHA256:(NSString* _Nullable)sumHex;
- (void)pinnedTLS12;
- (void)restrictedTLS;
- (void)trySocks5:(int32_t)port;
@end

@interface LibboxHTTPRequest : NSObject <goSeqRefInterface, LibboxHTTPRequest> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<LibboxHTTPResponse> _Nullable)execute:(NSError* _Nullable* _Nullable)error;
- (void)randomUserAgent;
- (void)setContent:(NSData* _Nullable)content;
- (void)setContentString:(NSString* _Nullable)content;
- (void)setHeader:(NSString* _Nullable)key value:(NSString* _Nullable)value;
- (void)setMethod:(NSString* _Nullable)method;
- (BOOL)setURL:(NSString* _Nullable)link error:(NSError* _Nullable* _Nullable)error;
- (void)setUserAgent:(NSString* _Nullable)userAgent;
@end

@interface LibboxHTTPResponse : NSObject <goSeqRefInterface, LibboxHTTPResponse> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (LibboxStringBox* _Nullable)getContent:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeTo:(NSString* _Nullable)path error:(NSError* _Nullable* _Nullable)error;
- (BOOL)writeToWithProgress:(NSString* _Nullable)path handler:(id<LibboxHTTPResponseWriteToProgressHandler> _Nullable)handler error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxHTTPResponseWriteToProgressHandler : NSObject <goSeqRefInterface, LibboxHTTPResponseWriteToProgressHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)update:(int64_t)progress total:(int64_t)total;
@end

@interface LibboxInt32Iterator : NSObject <goSeqRefInterface, LibboxInt32Iterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (int32_t)next;
@end

@interface LibboxInterfaceUpdateListener : NSObject <goSeqRefInterface, LibboxInterfaceUpdateListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)updateDefaultInterface:(NSString* _Nullable)interfaceName interfaceIndex:(int32_t)interfaceIndex isExpensive:(BOOL)isExpensive isConstrained:(BOOL)isConstrained;
@end

@interface LibboxLocalDNSTransport : NSObject <goSeqRefInterface, LibboxLocalDNSTransport> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)exchange:(LibboxExchangeContext* _Nullable)ctx message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
- (BOOL)lookup:(LibboxExchangeContext* _Nullable)ctx network:(NSString* _Nullable)network domain:(NSString* _Nullable)domain error:(NSError* _Nullable* _Nullable)error;
- (BOOL)raw;
@end

@interface LibboxLogIterator : NSObject <goSeqRefInterface, LibboxLogIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (LibboxLogEntry* _Nullable)next;
@end

@interface LibboxNeighborEntryIterator : NSObject <goSeqRefInterface, LibboxNeighborEntryIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxNeighborEntry* _Nullable)next;
@end

@interface LibboxNeighborUpdateListener : NSObject <goSeqRefInterface, LibboxNeighborUpdateListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)updateNeighborTable:(id<LibboxNeighborEntryIterator> _Nullable)entries;
@end

@interface LibboxNetworkInterfaceIterator : NSObject <goSeqRefInterface, LibboxNetworkInterfaceIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxNetworkInterface* _Nullable)next;
@end

@interface LibboxNetworkQualityTestHandler : NSObject <goSeqRefInterface, LibboxNetworkQualityTestHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)message;
- (void)onProgress:(LibboxNetworkQualityProgress* _Nullable)progress;
- (void)onResult:(LibboxNetworkQualityResult* _Nullable)result;
@end

@interface LibboxOnDemandRule : NSObject <goSeqRefInterface, LibboxOnDemandRule> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<LibboxStringIterator> _Nullable)dnsSearchDomainMatch;
- (id<LibboxStringIterator> _Nullable)dnsServerAddressMatch;
- (int32_t)interfaceTypeMatch;
- (NSString* _Nonnull)probeURL;
- (id<LibboxStringIterator> _Nullable)ssidMatch;
- (int32_t)target;
@end

@interface LibboxOnDemandRuleIterator : NSObject <goSeqRefInterface, LibboxOnDemandRuleIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (id<LibboxOnDemandRule> _Nullable)next;
@end

@interface LibboxOutboundGroupItemIterator : NSObject <goSeqRefInterface, LibboxOutboundGroupItemIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxOutboundGroupItem* _Nullable)next;
@end

@interface LibboxOutboundGroupIterator : NSObject <goSeqRefInterface, LibboxOutboundGroupIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxOutboundGroup* _Nullable)next;
@end

@interface LibboxPlatformInterface : NSObject <goSeqRefInterface, LibboxPlatformInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)autoDetectInterfaceControl:(int32_t)fd error:(NSError* _Nullable* _Nullable)error;
- (BOOL)checkPlatformShell:(NSError* _Nullable* _Nullable)error;
- (void)clearDNSCache;
- (BOOL)closeDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)closeNeighborMonitor:(id<LibboxNeighborUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxBridgeSession> _Nullable)createBridge:(LibboxBridgeOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
- (LibboxConnectionOwner* _Nullable)findConnectionOwner:(int32_t)ipProtocol sourceAddress:(NSString* _Nullable)sourceAddress sourcePort:(int32_t)sourcePort destinationAddress:(NSString* _Nullable)destinationAddress destinationPort:(int32_t)destinationPort error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxNetworkInterfaceIterator> _Nullable)getInterfaces:(NSError* _Nullable* _Nullable)error;
- (BOOL)includeAllNetworks;
- (id<LibboxLocalDNSTransport> _Nullable)localDNSTransport;
- (NSString* _Nonnull)lookupSFTPServer:(NSError* _Nullable* _Nullable)error;
- (LibboxPlatformUser* _Nullable)lookupUser:(NSString* _Nullable)username error:(NSError* _Nullable* _Nullable)error;
- (id<LibboxShellSession> _Nullable)openShellSession:(LibboxPlatformUser* _Nullable)user command:(NSString* _Nullable)command environ:(id<LibboxStringIterator> _Nullable)environ term:(NSString* _Nullable)term rows:(int32_t)rows cols:(int32_t)cols error:(NSError* _Nullable* _Nullable)error;
- (BOOL)openTun:(id<LibboxTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)readSystemSSHHostKey:(NSError* _Nullable* _Nullable)error;
- (LibboxWIFIState* _Nullable)readWIFIState;
- (void)registerMyInterface:(NSString* _Nullable)name;
- (BOOL)sendNotification:(LibboxNotification* _Nullable)notification error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startDefaultInterfaceMonitor:(id<LibboxInterfaceUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (BOOL)startNeighborMonitor:(id<LibboxNeighborUpdateListener> _Nullable)listener error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)tailscaleHostname;
- (BOOL)underNetworkExtension;
- (BOOL)usePlatformAutoDetectInterfaceControl;
- (BOOL)usePlatformBridge;
- (BOOL)usePlatformShell;
- (BOOL)useProcFS;
@end

@interface LibboxProfilePreviewIterator : NSObject <goSeqRefInterface, LibboxProfilePreviewIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxProfilePreview* _Nullable)next;
@end

@interface LibboxRoutePrefixIterator : NSObject <goSeqRefInterface, LibboxRoutePrefixIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxRoutePrefix* _Nullable)next;
@end

@interface LibboxSTUNTestHandler : NSObject <goSeqRefInterface, LibboxSTUNTestHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)message;
- (void)onProgress:(LibboxSTUNTestProgress* _Nullable)progress;
- (void)onResult:(LibboxSTUNTestResult* _Nullable)result;
@end

@interface LibboxShellSession : NSObject <goSeqRefInterface, LibboxShellSession> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (int32_t)masterFD;
- (BOOL)resize:(int32_t)rows cols:(int32_t)cols error:(NSError* _Nullable* _Nullable)error;
- (BOOL)signal:(int32_t)signal error:(NSError* _Nullable* _Nullable)error;
- (BOOL)waitExit:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

@interface LibboxStringIterator : NSObject <goSeqRefInterface, LibboxStringIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (int32_t)len;
- (NSString* _Nonnull)next;
@end

@interface LibboxTailscaleEndpointStatusIterator : NSObject <goSeqRefInterface, LibboxTailscaleEndpointStatusIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxTailscaleEndpointStatus* _Nullable)next;
@end

@interface LibboxTailscalePeerIterator : NSObject <goSeqRefInterface, LibboxTailscalePeerIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxTailscalePeer* _Nullable)next;
@end

@interface LibboxTailscalePingHandler : NSObject <goSeqRefInterface, LibboxTailscalePingHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)message;
- (void)onPingResult:(LibboxTailscalePingResult* _Nullable)result;
@end

@interface LibboxTailscaleSSHHandler : NSObject <goSeqRefInterface, LibboxTailscaleSSHHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onAuthBanner:(NSString* _Nullable)message;
- (void)onError:(NSString* _Nullable)message;
- (void)onExit:(int32_t)exitCode signal:(NSString* _Nullable)signal errorMessage:(NSString* _Nullable)errorMessage;
- (void)onOutput:(NSData* _Nullable)data;
- (void)onReady;
@end

@interface LibboxTailscaleStatusHandler : NSObject <goSeqRefInterface, LibboxTailscaleStatusHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)message;
- (void)onStatusUpdate:(LibboxTailscaleStatusUpdate* _Nullable)status;
@end

@interface LibboxTailscaleUserGroupIterator : NSObject <goSeqRefInterface, LibboxTailscaleUserGroupIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxTailscaleUserGroup* _Nullable)next;
@end

@interface LibboxTunOptions : NSObject <goSeqRefInterface, LibboxTunOptions> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)getAutoRoute;
- (LibboxStringBox* _Nullable)getDNSMode;
- (id<LibboxStringIterator> _Nullable)getDNSServerAddress:(NSError* _Nullable* _Nullable)error;
- (id<LibboxStringIterator> _Nullable)getExcludePackage;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyBypassDomain;
- (id<LibboxStringIterator> _Nullable)getHTTPProxyMatchDomain;
- (NSString* _Nonnull)getHTTPProxyServer;
- (int32_t)getHTTPProxyServerPort;
- (id<LibboxStringIterator> _Nullable)getIncludePackage;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet4RouteRange;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6Address;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteExcludeAddress;
- (id<LibboxRoutePrefixIterator> _Nullable)getInet6RouteRange;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
- (BOOL)isHTTPProxyEnabled;
@end

@interface LibboxUSBIPServerStatusHandler : NSObject <goSeqRefInterface, LibboxUSBIPServerStatusHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)message;
- (void)onStatusUpdate:(LibboxUSBIPServerStatusUpdate* _Nullable)status;
@end

@interface LibboxUSBIPServerStatusIterator : NSObject <goSeqRefInterface, LibboxUSBIPServerStatusIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxUSBIPServerStatus* _Nullable)next;
@end

@interface LibboxUSBLocalDeviceInfoIterator : NSObject <goSeqRefInterface, LibboxUSBLocalDeviceInfoIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxUSBLocalDeviceInfo* _Nullable)next;
@end

@interface LibboxUSBLocalProviderHandler : NSObject <goSeqRefInterface, LibboxUSBLocalProviderHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onDeviceError:(NSString* _Nullable)serverTag deviceID:(NSString* _Nullable)deviceID message:(NSString* _Nullable)message;
- (void)onLocalDevicesChanged;
- (void)onSessionError:(NSString* _Nullable)serverTag message:(NSString* _Nullable)message;
@end

@interface LibboxUSBProviderHandler : NSObject <goSeqRefInterface, LibboxUSBProviderHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onAbort:(NSString* _Nullable)deviceID endpoint:(int32_t)endpoint;
- (void)onError:(NSString* _Nullable)deviceID message:(NSString* _Nullable)message;
- (void)onReady:(NSString* _Nullable)deviceID busID:(NSString* _Nullable)busID;
- (void)onURBRequest:(LibboxUSBURBRequest* _Nullable)request;
@end

@interface LibboxUSBSharedDeviceInterfaceIterator : NSObject <goSeqRefInterface, LibboxUSBSharedDeviceInterfaceIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxUSBSharedDeviceInterface* _Nullable)next;
@end

@interface LibboxUSBSharedDeviceIterator : NSObject <goSeqRefInterface, LibboxUSBSharedDeviceIterator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)hasNext;
- (LibboxUSBSharedDevice* _Nullable)next;
@end

@interface LibboxXPCDialer : NSObject <goSeqRefInterface, LibboxXPCDialer> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)dialXPC:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

#endif
